USE bielozertsev;



CREATE TABLE IF NOT EXISTS GROUP_ID (
ID           NVARCHAR(10) NOT NULL PRIMARY KEY,
TITLE        NVARCHAR(200) NOT NULL
);


CREATE TABLE IF NOT EXISTS STUDENT (
ID           INT AUTO_INCREMENT PRIMARY KEY,
SURNAME      VARCHAR(200) NOT NULL,
AGE          INT NOT NULL,
GROUP_ID     NVARCHAR(10),
FOREIGN KEY (GROUP_ID) REFERENCES GROUP_ID (ID) 
);




INSERT INTO GROUP_ID (ID, TITLE) 
     VALUES ('EO-22-1','EO-22-1 "Облік і оподаткування"');
     


INSERT INTO STUDENT (SURNAME, AGE, GROUP_ID) 
     VALUES ('Ivanko','18', 'EO-22-1');
INSERT INTO STUDENT (SURNAME, AGE, GROUP_ID) 
     VALUES ('Grinkov','17', 'EO-22-1');
INSERT INTO STUDENT (SURNAME, AGE, GROUP_ID) 
     VALUES ('Bojko','20', 'EO-22-1');

SELECT *
FROM GROUP_ID;
